### ISSUE TITLE
Changing speeds

### ISSUE THREAD

**Issue by illillli** [Tbsc/TbscClick#3]
Would you mind adding a button to change the speeds quicker or slower? (or, adding a slower speed )
If I can attack on a lower speed, that would be great.

Really appreciate your replying.

**Comment by Tbsc** [comment]
Great suggestion. I began implementing it, starting with 1.16. It will soon be up.

**Comment by illillli** [comment]
It's really nice to hear that.
Thank you so much.

Tbsc ***@***.***> 於 2021年5月19日 週三 20:23 寫道：

**Comment by Tbsc** [comment]
Now also up for 1.12, closing this issue.
