### ISSUE TITLE
Problem with auto right click in 1.16.5 latest virsion

### ISSUE THREAD

**Issue by RealLakshyaK2011** [Tbsc/TbscClick#4]
when i was playing, i by mistake i open a chest using auto right click and when i press esc, it opens the chest gui again.
So make this mod like this that it stops its all function when a gui is opened, e.g. -> auto left click is on then i opened the gui then it automaticly stops auto left click function till i use it again.
Please Solve This

**Comment by Tbsc** [comment]
Good suggestion, it's something I've wanted to solve in the past but haven't. I will upload a fix soon

**Comment by Tbsc** [comment]
Version 2.3.0 of the mod has been uploaded and has this fixed, try it now.
