### ISSUE TITLE
Clicking Intervals

### ISSUE THREAD

**Issue by Br3xinn** [Tbsc/TbscClick#6]
I was wondering if there was any way to click at a slower interval than 10 ticks? Is there any way I can maybe change this manually through the files?

**Comment by Tbsc** [comment]
There will be soon, this is a nice addition that I've begun working on. You'll be able to set the minimum, maximum and step of the auto click interval, in a regular config file.

**Comment by Br3xinn** [comment]
ok ty dude, btw the GUI detection is awesome!

**Comment by Tbsc** [comment]
Thank you for using and supporting the mod. 
I finished building the new feature, and updated versions of the mod for all supported Minecraft versions are up on CurseForge and here on GitHub.
Regarding that GUI detection, I've changed it a little, so now it won't stop auto-clicking when the opened GUI is just the pause menu. With all other GUIs, the detection stays the same. This is the intended behavior.
