### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Addiee-o** [Tbsc/TbscClick#8]
https://user-images.githubusercontent.com/109289586/178984839-a3fc280c-4388-4d1b-bf80-4f07f4b2d4d7.gif

It says "TbscClick-v2.4.0-mc1.18.jar needs a language provider javafml:39 or above to load" then underneath it says "we have found 38" I'm confused.
I've restarted the launcher and it's still saying this

**Comment by Epicjii** [comment]
You have the wrong version of forge. That version of the mod needs forge 39 which is for 1.18.1

**Comment by Tbsc** [comment]
Just as they said, TbscClick supports 1.18.1 and 1.18.2, not 1.18. Update your Minecraft installation to the latest 1.18 patch and Forge to the matching version to use the mod.
