### ISSUE TITLE
Fabric

### ISSUE THREAD

**Issue by kit-nine** [Tbsc/TbscClick#9]
Any chance this could get ported to Fabric? This is the best autoclicking mod on CurseForge I could find, but it's only on Forge so I can't use it with the rest of my pack for Phoenix Anarchy.
Thanks for consideration.

**Comment by Tbsc** [comment]
Unfortunately, I don't have nor will have time I can afford to spend porting it to a whole new mod loader. Updating it with the versions is fairly easy but this is too much work for me right now. Sorry.
